Migrated run script to bash

diff --git a/bin/run_optimization_tutorial_examples b/bin/run_optimization_tutorial_examples
--- a/bin/run_optimization_tutorial_examples
+++ b/bin/run_optimization_tutorial_examples
@@ -1,140 +1,15 @@
-#!/usr/bin/env -S tcsh -f
+#!/usr/bin/env bash
 
 # Copyright (C) 2025-2026 Dmitry Messerman
 # SPDX-License-Identifier: GPL-3.0
 
-set script_path=`realpath $0 | xargs dirname`
-set script_name=`realpath $0 | xargs basename`
-set package=pyoptiwize
-set version=python3.12
-set wheel=pyoptiwize
-while($#argv > 0 )
-    set opt="$argv[1]"
-    shift
-    switch($opt)
-        case "-h":
-        case "--help":
-             goto help
-        case "-clean":
-            \rm -rf venv* >& /dev/null
-            exit 0
-        case "-w":
-        case "--from_wheel":
-            set from_wheel
-            breaksw
-        case "-r":
-        case "--force_reinstall":
-            set reinstall
-            breaksw
-        case "-p":
-        case "--python_version":
-            set version="$argv[1]"
-            shift
-            if( $version !~ "python3.1[1-3]" ) then
-                echo "\nERROR: only python versions python3.11, python3.12 and python3.13 are supported\n"
-                exit(1)
-            endif
-            breaksw
-        case "-j":
-        case "--jupyter":
-            set run_jupyter
-            breaksw
-        default:
-            echo "\nERROR: switch $opt is not supported\n"
-            goto help
-    endsw
-end
-xset q >& /dev/null
-if($status) then
-    echo "\nWARINING: GUI is not available"
-    echo "Opening virtual display"
-    $script_path/open_virtual_display
-    if($status) then
-        echo "\nERROR: failed to open virtual display. Exiting ...\n"
-        exit 1
-    endif
-    setenv DISPLAY :99
-endif
-set version_digits=`echo $version | tr -d '[a-z].'`
-set log=$PWD/${script_name}_${version_digits}.log
-set prompt='%U%m%u:%B%~%b%#'
-set venv_root="venv_${version_digits}"
-if(! -f $venv_root/bin/activate.csh ) then
-    echo "Establishing python virtual environment in $PWD/${venv_root} directory"
-    ${version} -m venv $venv_root
-else
-    echo "Virtual environment in $PWD/${venv_root} directory already exists"
-endif
-source ${venv_root}/bin/activate.csh
-pip show -q ${package}
-set package_status=$status
-if($?run_jupyter) then
-    pip show -q notebook
-    set extra_status=$status
-else
-    @ extra_status = 0
-    foreach test_package (pytest pytest-forked pytest-mock)
-        pip show -q $test_package
-        @ extra_status = $extra_status + $status
-    end
-endif
-if($package_status || $extra_status || $?reinstall) then
-    if( $?reinstall) then
-        echo "Reinstalling $package ..."
-    else
-        echo "Installing $package ..."
-    endif
-    if($?from_wheel) then
-        echo "From wheel: $wheel"
-        if( $?run_jupyter ) then
-            (set noglob; pip install "$wheel"[notebook])
-        else
-            (set noglob; pip install "$wheel"[test])
-        endif
-    else
-        set repo=/tmp/${package}_repo_$$
-        \rm -rf $repo >& /dev/null
-        git clone https://git@github.com/mdmitry1/optimization-tutorial $repo
-        if( $?run_jupyter ) then
-            (set noglob; pip install "$repo"[notebook])
-        else
-            (set noglob; pip install "$repo"[test])
-        endif
-    endif
-else
-    echo "$package has been already installed, `pip show -V $package | grep Version`"
-endif
-set rundir=/tmp/optimization_tutorial_${USER}_$$
-echo "Run directory: $rundir" |& tee $log
-\rm -rf $rundir >& /dev/null
-mkdir -p $rundir
-cd $rundir
-set python_path=`which python`
-set venv_path=$python_path:h:h
-echo $venv_path
-\rm -rf $venv_path/lib/${version}/site-packages/*mathsat* >& /dev/null
-\cp -p /usr/local/lib/${version}/dist-packages/*mathsat* $venv_path/lib/${version}/site-packages
-\rm -rf $venv_path/lib/${version}/site-packages/z3 >& /dev/null
-\cp -rp /usr/lib/python3/dist-packages/z3 $venv_path/lib/${version}/site-packages
-\cp -rp $venv_path/lib/${version}/site-packages/${package} .
-if( $?run_jupyter ) then
-    cd $package/examples
-    set cmd="env PYTHONDONTWRITEBYTECODE=1 jupyter-notebook --ip 0.0.0.0"
-    if( -f /.dockerenv ) then
-        set cmd="$cmd --no-browser --port=8888 --allow-root"
-    endif
-    echo $cmd |& tee -a $log
-    $cmd |& tee -a $log
-else
-    set cmd="env PYTHONDONTWRITEBYTECODE=1 pytest -v --forked -m forked $PWD/${package}/examples"
-    echo $cmd |& tee -a $log
-    $cmd |& tee -a $log
-    set cmd="env PYTHONDONTWRITEBYTECODE=1 pytest -v -s -m 'not forked' $PWD/${package}/examples"
-    echo $cmd | tr '\047' '"' |& tee -a $log
-    echo $cmd | tr '\047' '"' | source /dev/stdin |& tee -a $log
-endif
-exit($status)
-help:
+script_path=$(dirname "$(realpath "$0")")
+script_name=$(basename "$(realpath "$0")")
+package=pyoptiwize
+version=python3.12
+wheel=pyoptiwize
+
+usage() {
     echo "$script_name [[-h|--help] | [-clean] | [-w|--from_wheel] [-r|--force_reinstall] [-p|--python_version <version>]"
     echo "                                   -h --help:             display this help message"
     echo "                                   -clean:                clean all workareas $PWD/venv_31*"
@@ -147,4 +22,149 @@ help:
     echo "Default python version:    python3.12"
     echo "Workarea root directory:   $PWD/venv_31[1|2|3]"
     echo ""
-    exit(1)
+    exit 1
+}
+
+from_wheel=
+reinstall=
+run_jupyter=
+
+while [[ $# -gt 0 ]]; do
+    opt="$1"
+    shift
+    case "$opt" in
+        -h|--help)
+            usage
+            ;;
+        -clean)
+            rm -rf venv* 2>/dev/null
+            exit 0
+            ;;
+        -w|--from_wheel)
+            from_wheel=1
+            ;;
+        -r|--force_reinstall)
+            reinstall=1
+            ;;
+        -p|--python_version)
+            version="$1"
+            shift
+            if [[ ! "$version" =~ ^python3\.1[1-3]$ ]]; then
+                echo -e "\nERROR: only python versions python3.11, python3.12 and python3.13 are supported\n"
+                exit 1
+            fi
+            ;;
+        -j|--jupyter)
+            run_jupyter=1
+            ;;
+        *)
+            echo -e "\nERROR: switch $opt is not supported\n"
+            usage
+            ;;
+    esac
+done
+
+xset q >/dev/null 2>&1
+if [[ $? -ne 0 ]]; then
+    echo -e "\nWARINING: GUI is not available"
+    echo "Opening virtual display"
+    "$script_path/open_virtual_display"
+    if [[ $? -ne 0 ]]; then
+        echo -e "\nERROR: failed to open virtual display. Exiting ...\n"
+        exit 1
+    fi
+    export DISPLAY=:99
+fi
+
+version_digits=$(echo "$version" | tr -d 'a-z.')
+if [[ -n "$run_jupyter" ]]; then
+    log="$PWD/${script_name}_${version_digits}_run_jupyter.log"
+else
+    log="$PWD/${script_name}_${version_digits}.log"
+fi
+venv_root="venv_${version_digits}"
+
+if [[ ! -f "$venv_root/bin/activate" ]]; then
+    echo "Establishing python virtual environment in $PWD/${venv_root} directory"
+    "${version}" -m venv "$venv_root"
+else
+    echo "Virtual environment in $PWD/${venv_root} directory already exists"
+fi
+
+source "${venv_root}/bin/activate"
+
+pip show -q "${package}"
+package_status=$?
+
+extra_status=0
+if [[ -n "$run_jupyter" ]]; then
+    pip show -q notebook
+    extra_status=$?
+else
+    for test_package in pytest pytest-forked pytest-mock; do
+        pip show -q "$test_package"
+        (( extra_status += $? ))
+    done
+fi
+
+if [[ $package_status -ne 0 || $extra_status -ne 0 || -n "$reinstall" ]]; then
+    if [[ -n "$reinstall" ]]; then
+        echo "Reinstalling $package ..."
+    else
+        echo "Installing $package ..."
+    fi
+    if [[ -n "$from_wheel" ]]; then
+        echo "From wheel: $wheel"
+        if [[ -n "$run_jupyter" ]]; then
+            pip install "${wheel}[notebook]"
+        else
+            pip install "${wheel}[test]"
+        fi
+    else
+        repo="/tmp/${package}_repo_$$"
+        rm -rf "$repo" 2>/dev/null
+        git clone https://git@github.com/mdmitry1/optimization-tutorial "$repo"
+        if [[ -n "$run_jupyter" ]]; then
+            pip install "${repo}[notebook]"
+        else
+            pip install "${repo}[test]"
+        fi
+    fi
+else
+    echo "$package has been already installed, $(pip show -V "$package" | grep Version)"
+fi
+
+rundir="/tmp/optimization_tutorial_${USER}_$$"
+echo "Run directory: $rundir" 2>&1 | tee "$log"
+rm -rf "$rundir" 2>/dev/null
+mkdir -p "$rundir"
+cd "$rundir"
+
+python_path=$(which python)
+venv_path=$(dirname "$(dirname "$python_path")")
+echo "$venv_path"
+
+rm -rf "${venv_path}/lib/${version}/site-packages/"*mathsat* 2>/dev/null
+cp -p /usr/local/lib/${version}/dist-packages/*mathsat* "${venv_path}/lib/${version}/site-packages"
+rm -rf "${venv_path}/lib/${version}/site-packages/z3" 2>/dev/null
+cp -rp /usr/lib/python3/dist-packages/z3 "${venv_path}/lib/${version}/site-packages"
+cp -rp "${venv_path}/lib/${version}/site-packages/${package}" .
+
+if [[ -n "$run_jupyter" ]]; then
+    cd "${package}/examples"
+    cmd="env PYTHONDONTWRITEBYTECODE=1 jupyter-notebook --ip 0.0.0.0"
+    if [[ -f /.dockerenv ]]; then
+        cmd="$cmd --no-browser --port=8888 --allow-root"
+    fi
+    echo "$cmd" 2>&1 | tee -a "$log"
+    eval "$cmd" 2>&1 | tee -a "$log"
+else
+    cmd="env PYTHONDONTWRITEBYTECODE=1 pytest -v --forked -m forked $PWD/${package}/examples"
+    echo "$cmd" 2>&1 | tee -a "$log"
+    eval "$cmd" 2>&1 | tee -a "$log"
+    cmd="env PYTHONDONTWRITEBYTECODE=1 pytest -v -s -m 'not forked' $PWD/${package}/examples"
+    echo "$cmd" | tr "'" '"' 2>&1 | tee -a "$log"
+    eval "$cmd" 2>&1 | tee -a "$log"
+fi
+
+exit $?
